# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scope_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScopeWindow(object):
    def setupUi(self, ScopeWindow):
        ScopeWindow.setObjectName("ScopeWindow")
        ScopeWindow.resize(990, 627)
        self.centralwidget = QtWidgets.QWidget(ScopeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scopeWidget = ScopeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scopeWidget.sizePolicy().hasHeightForWidth())
        self.scopeWidget.setSizePolicy(sizePolicy)
        self.scopeWidget.setObjectName("scopeWidget")
        self.horizontalLayout.addWidget(self.scopeWidget)
        self.controlsWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsWidget.sizePolicy().hasHeightForWidth())
        self.controlsWidget.setSizePolicy(sizePolicy)
        self.controlsWidget.setObjectName("controlsWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(192, 96))
        self.groupBox.setObjectName("groupBox")
        self.triggerLevelDial = QtWidgets.QDial(self.groupBox)
        self.triggerLevelDial.setGeometry(QtCore.QRect(110, 20, 71, 64))
        self.triggerLevelDial.setMinimum(-100)
        self.triggerLevelDial.setMaximum(100)
        self.triggerLevelDial.setObjectName("triggerLevelDial")
        self.triggerLevelEdit = QtWidgets.QLineEdit(self.groupBox)
        self.triggerLevelEdit.setEnabled(True)
        self.triggerLevelEdit.setGeometry(QtCore.QRect(10, 50, 81, 25))
        self.triggerLevelEdit.setMaxLength(6)
        self.triggerLevelEdit.setFrame(False)
        self.triggerLevelEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.triggerLevelEdit.setReadOnly(True)
        self.triggerLevelEdit.setObjectName("triggerLevelEdit")
        self.verticalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignTop)
        self.listenButton = QtWidgets.QPushButton(self.controlsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listenButton.sizePolicy().hasHeightForWidth())
        self.listenButton.setSizePolicy(sizePolicy)
        self.listenButton.setCheckable(True)
        self.listenButton.setChecked(False)
        self.listenButton.setFlat(False)
        self.listenButton.setObjectName("listenButton")
        self.verticalLayout.addWidget(self.listenButton, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.controlsWidget)
        ScopeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ScopeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 26))
        self.menubar.setObjectName("menubar")
        ScopeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ScopeWindow)
        self.statusbar.setObjectName("statusbar")
        ScopeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ScopeWindow)
        QtCore.QMetaObject.connectSlotsByName(ScopeWindow)

    def retranslateUi(self, ScopeWindow):
        _translate = QtCore.QCoreApplication.translate
        ScopeWindow.setWindowTitle(_translate("ScopeWindow", "Audio Scope"))
        self.groupBox.setTitle(_translate("ScopeWindow", "Trigger"))
        self.triggerLevelEdit.setText(_translate("ScopeWindow", "0"))
        self.listenButton.setText(_translate("ScopeWindow", "Listen"))
from scope_widget import ScopeWidget
