# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scope_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScopeWindow(object):
    def setupUi(self, ScopeWindow):
        ScopeWindow.setObjectName("ScopeWindow")
        ScopeWindow.resize(838, 503)
        self.centralwidget = QtWidgets.QWidget(ScopeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scopeWidget = ScopeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scopeWidget.sizePolicy().hasHeightForWidth())
        self.scopeWidget.setSizePolicy(sizePolicy)
        self.scopeWidget.setObjectName("scopeWidget")
        self.horizontalLayout.addWidget(self.scopeWidget)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(192, 96))
        self.groupBox.setObjectName("groupBox")
        self.dial = QtWidgets.QDial(self.groupBox)
        self.dial.setGeometry(QtCore.QRect(110, 20, 71, 64))
        self.dial.setObjectName("dial")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 81, 25))
        self.lineEdit.setMaxLength(6)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignTop)
        ScopeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ScopeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 26))
        self.menubar.setObjectName("menubar")
        ScopeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ScopeWindow)
        self.statusbar.setObjectName("statusbar")
        ScopeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ScopeWindow)
        QtCore.QMetaObject.connectSlotsByName(ScopeWindow)

    def retranslateUi(self, ScopeWindow):
        _translate = QtCore.QCoreApplication.translate
        ScopeWindow.setWindowTitle(_translate("ScopeWindow", "Audio Scope"))
        self.groupBox.setTitle(_translate("ScopeWindow", "Trigger"))
from scope_widget import ScopeWidget
